//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOrder
    {
        public int OrderID { get; set; }
        public string OrderName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderQuantity { get; set; }
        public string OrderShipment { get; set; }
        public int OUserID { get; set; }
        public int OProductID { get; set; }
        public string OrderIamge { get; set; }
    }
}
