//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class MProduct
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProdcutQuantity { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<System.DateTime> ProductDate { get; set; }
        public string ProductIamge { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
